// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AttachWindow(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(998837968, window);
}

export function ConnectNow(): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(4223432003);
}

export function CurrentState(): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(2154854551);
}

export function DisconnectNow(): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(2894459725);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(2563497885);
}

export function ReconnectStatus(): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(3513197952);
}

export function SaveSettings(input: $models.SettingsInput): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(1622260973, input);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3854130376);
}

export function ToggleLaunchAtLogin(enabled: boolean): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(1672786536, enabled);
}
