// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopApp from "./desktopapp.js";
export {
    DesktopApp
};

export type {
    DesktopState,
    SettingsInput
} from "./models.js";
