// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DesktopState {
    "phase": string;
    "message": string;
    "online": boolean;
    "username": string;
    "endpoint": string;
    "acid": string;
    "checkIntervalSeconds": number;
    "autoConnect": boolean;
    "autoReconnect": boolean;
    "launchAtLogin": boolean;
}

export interface SettingsInput {
    "username": string;
    "password": string;
    "endpoint": string;
    "acid": string;
    "checkIntervalSeconds": number;
    "autoConnect": boolean;
    "autoReconnect": boolean;
    "launchAtLogin": boolean;
}
