project_name: hdu-cli

builds:
  - id: linux-cli
    main: ./main.go
    binary: hdu-cli
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: linux-cli-archive
    ids:
      - linux-cli
    formats:
      - tar.gz
    name_template: "{{ .Binary }}_{{ .Os | title }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - scripts/install-linux.sh
      - scripts/uninstall-linux.sh

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
